In [93]:
import numpy as np

<h2>Least Square Method</h2>

In [94]:
def LSM(A, b):
    ATA = A.T @ A
    ATb = A.T @ b 
    Ls = np.linalg.inv(ATA) @ ATb   
    is_b = A @ Ls
    error_vector = b - is_b
    total = 0
    for num in error_vector:
        total += num**2
    error = np.sqrt(total)
    print("Least Square Solution:\n",Ls)
    print("Error Vector:\n", error_vector)
    print("Error:", error[0])
    #return Ls, error_vector, error[0] 

In [95]:
A = np.array([
    [1, -1],
    [3, 2],
    [-2, 4]])
b = np.array([
    [4],
    [1],
    [3]])

In [96]:
LSM(A, b)

Least Square Solution:
 [[0.17894737]
 [0.50175439]]
Error Vector:
 [[ 4.32280702]
 [-0.54035088]
 [ 1.35087719]]
Error: 4.561086358745012


<h2>Curve Fitting</h2>

In [97]:
points = np.array([
    #x,y
    [0,1],
    [1,3],
    [2,4],
    [3,4]
])

# aX + b = y
A = np.array([
    #a_coef(x),b_coef
    [0,1],
    [1,1],
    [2,1],
    [3,1]
])

b = np.array([
    [1],[3],[4],[4]
])

LSM(A, b)

Least Square Solution:
 [[1. ]
 [1.5]]
Error Vector:
 [[-0.5]
 [ 0.5]
 [ 0.5]
 [-0.5]]
Error: 1.0
